package com.beigu.yunbeiuc.datagen;

import com.beigu.yunbeiuc.block.MunicipalBlocks;
import com.beigu.yunbeiuc.block.RoadBlocks;
import com.beigu.yunbeiuc.block.SignBlocks;
import com.beigu.yunbeiuc.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class ModZhCnLangProvider extends FabricLanguageProvider {
    public ModZhCnLangProvider(FabricDataOutput dataOutput) {
        super(dataOutput,"zh_cn");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModItems.WAND,"魔杖");
        translationBuilder.add(ModItems.TREE_WAND,"树木魔杖");
        translationBuilder.add(ModItems.LINK_WAND,"链接魔杖");
        translationBuilder.add("item.yunbeiuc.tree_wand.tooltip","右键点击草方块或泥土方块以种植一棵橡树");
        translationBuilder.add("item.yunbeiuc.tree_wand.success","成功种植了一棵橡树!");
        translationBuilder.add("item.yunbeiuc.tree_wand.planted_sapling","种植了一棵橡树苗!");
        translationBuilder.add("item.yunbeiuc.tree_wand.failed","无法在此处生成橡树!");
        translationBuilder.add("item.yunbeiuc.tree_wand.no_space","没有足够的空间种植树木!");
        translationBuilder.add("item.yunbeiuc.tree_wand.invalid_block","无法在这个方块上种植树木!");
        translationBuilder.add(ModItems.WATER_WAND,"水源魔杖");
        translationBuilder.add("item.yunbeiuc.water_wand.tooltip","右键点击3*3*3范围内替换为水源");
        translationBuilder.add("item.yunbeiuc.water_wand.success","成功替换成水源!");
        translationBuilder.add(ModItems.ROTATED_WAND,"旋转魔杖");
        translationBuilder.add("item.yunbeiuc.rotated_wand.tooltip","右键点击方块以顺时针旋转90度");

// 交通信号灯类
        translationBuilder.add(MunicipalBlocks.TRAFFIC_LIGHTS_STRAIGHT, "直行交通信号灯");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_LIGHTS_LEFT, "左转交通信号灯");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_LIGHTS_PAVEMENT, "人行道交通信号灯");
        translationBuilder.add("block.yunbeiuc.traffic_lights.tooltip","手持魔杖右键点击以切换交通信号灯的状态");

// 道路设施类
        translationBuilder.add(MunicipalBlocks.ROAD_FLOWER_BOX_1, "道路花箱1型");
        translationBuilder.add(MunicipalBlocks.ROAD_FLOWER_BOX_2, "道路花箱2型");
        translationBuilder.add(MunicipalBlocks.ROAD_FLOWER_BOX_2_FENCE, "道路花箱2型围栏");

// 道路监控设备类
        translationBuilder.add(MunicipalBlocks.ROAD_DETECTION_CAMERA, "道路检测/测速监控摄像头");
        translationBuilder.add(MunicipalBlocks.ROAD_LIGHTING_LAMP, "道路补光灯");
        translationBuilder.add("block.yunbeiuc.lighting_lamp.tooltip","手持魔杖右键点击以切换灯光状态");
        translationBuilder.add(MunicipalBlocks.ROAD_RADAR_SPEED_DETECTOR, "雷达测速器");
        translationBuilder.add("block.yunbeiuc.radar_speed_detector.tooltip","手持魔杖右键点击以切换灯光状态");

// 道路安全设施类
        translationBuilder.add(MunicipalBlocks.TRAFFIC_CONE, "交通锥");
        translationBuilder.add(MunicipalBlocks.ROAD_COLLISION_BARREL, "道路防撞桶");
        translationBuilder.add(MunicipalBlocks.WATER_SAFETY_BARRIER_RED, "红色水上安全护栏");

// 环卫设施类
        translationBuilder.add(MunicipalBlocks.RUBBISH_BIN_WHITE, "白色垃圾桶");
        translationBuilder.add(MunicipalBlocks.RUBBISH_BIN_GRAY_GREEN, "灰绿色垃圾桶");
        translationBuilder.add("block.yunbeiuc.rubbish_bin.tooltip","手持魔杖右键清空垃圾桶");

// 道路标线/障碍类
        translationBuilder.add(MunicipalBlocks.SPEED_BUMP, "减速带");
        translationBuilder.add(MunicipalBlocks.VIBRATION_MARKING_LINE, "振动标线");
        translationBuilder.add(MunicipalBlocks.PARKING_SPACE_BARRIER, "车位地锁");

// 龙门架类
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_SIDE, "龙门架侧架");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_CONNECTION, "龙门架连接件");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_MAIN, "龙门架主架");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_RAILING, "龙门架栏杆");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_LADDER, "龙门架爬梯");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_LED_SIDE, "龙门架侧装LED专用");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_LED_MAIN, "龙门架主装LED专用");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_LED,"龙门架LED屏");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_DETECTION_CAMERA,"龙门架检测/测速监控摄像头");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_LIGHTING_LAMP,"龙门架道路补光灯");
        translationBuilder.add(MunicipalBlocks.GANTRY_FRAME_RADAR_SPEED_DETECTOR,"龙门架雷达测速器");

        translationBuilder.add(MunicipalBlocks.HEIGHT_LIMIT_BARRIER_SIDE, "限高杆侧架");
        translationBuilder.add(MunicipalBlocks.HEIGHT_LIMIT_BARRIER_CONNECTION, "限高杆连接件");
        translationBuilder.add(MunicipalBlocks.HEIGHT_LIMIT_BARRIER_MAIN, "限高杆主架");

// 防眩设施类
        translationBuilder.add(MunicipalBlocks.ANTI_GLARE_NET, "防眩网");
        translationBuilder.add(MunicipalBlocks.ANTI_GLARE_NET_POLE, "防眩网立柱");
        translationBuilder.add(MunicipalBlocks.ANTI_GLARE_VERSION, "防眩板");

// 交通护栏类
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER, "交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_YELLOW_DOUBLE, "黄色双体交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_YELLOW, "黄色交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_RED, "红色交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_RED_DOUBLE, "红色双体交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_OBLIQUE, "斜向交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY, "灰色交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_OBLIQUE, "灰色斜向交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_RED, "红灰色交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_RED_OBLIQUE,"红灰色斜向交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_YELLOW, "黄灰色交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_YELLOW_OBLIQUE, "黄灰色斜向交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_SLANT, "灰色倾斜交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_SLANT_YELLOW, "黄灰色倾斜交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_SLANT_RED, "红灰色倾斜交通护栏");
        translationBuilder.add(MunicipalBlocks.TRAFFIC_BARRIER_GRAY_SLANT_OBLIQUE, "灰色斜向倾斜交通护栏");

// 道路警示柱类
        translationBuilder.add(MunicipalBlocks.ROAD_WARNING_POLE_RED, "红色道路警示柱");
        translationBuilder.add(MunicipalBlocks.ROAD_WARNING_POLE_YELLOW, "黄色道路警示柱");
        translationBuilder.add(MunicipalBlocks.ROAD_WARNING_POLE_GREEN, "绿色道路警示柱");

// 铁马护栏类
        translationBuilder.add(MunicipalBlocks.IRON_HORSE_YELLOW, "黄色铁马护栏");
        translationBuilder.add(MunicipalBlocks.IRON_HORSE_RED, "红色铁马护栏");
        translationBuilder.add(MunicipalBlocks.IRON_HORSE_WHITE, "白色铁马护栏");
        translationBuilder.add(MunicipalBlocks.IRON_HORSE_GRAY, "灰色铁马护栏");

// 反光标识类
        translationBuilder.add(MunicipalBlocks.REFLECTIVE_SIGN_YELLOW_ALL_1, "黄色全反光标识1型");
        translationBuilder.add(MunicipalBlocks.REFLECTIVE_SIGN_YELLOW_ALL_2, "黄色全反光标识2型");
        translationBuilder.add(MunicipalBlocks.REFLECTIVE_SIGN_RED_ALL_1, "红色全反光标识1型");
        translationBuilder.add(MunicipalBlocks.REFLECTIVE_SIGN_RED_ALL_2, "红色全反光标识2型");

// 仪器杆类
        translationBuilder.add(MunicipalBlocks.INSTRUMENT_POLE_FOUNDATIONS, "仪器杆基础");
        translationBuilder.add(MunicipalBlocks.INSTRUMENT_POLE_LONGITUDINAL, "纵向仪器杆");
        translationBuilder.add(MunicipalBlocks.INSTRUMENT_CAMERA, "仪器摄像头");
        translationBuilder.add(MunicipalBlocks.INSTRUMENT_FEE_DISPLAY, "车辆信息显示屏");
        translationBuilder.add(MunicipalBlocks.INSTRUMENT_LANE_INDICATOR, "车道指示器");

        translationBuilder.add(MunicipalBlocks.BARRIER_GATE_1_MAIN,"道闸1型");
        translationBuilder.add(MunicipalBlocks.BARRIER_GATE_1_MAIN_SLAB,"道闸1台阶型");
        translationBuilder.add(MunicipalBlocks.BARRIER_GATE_1_POLE_HORIZONTAL,"横向道闸杆1型");
        translationBuilder.add(MunicipalBlocks.BARRIER_GATE_1_POLE_LONGITUDINAL,"纵向道闸杆1型");

// 安全岛类
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_1, "黄色安全岛1型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_2, "黄色安全岛2型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_3, "黄色安全岛3型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_4, "黄色安全岛4型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_GRAY, "灰色安全岛");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_OBLIQUE_1, "黄色斜向安全岛1型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_OBLIQUE_2, "黄色斜向安全岛2型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_GRAY_OBLIQUE, "灰色斜向安全岛");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_SLAB_EDGE_1, "黄色安全岛石板边缘1型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_SLAB_EDGE_2, "黄色安全岛石板边缘2型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_SLAB_EDGE_3, "黄色安全岛石板边缘3型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_SLAB_EDGE_4, "黄色安全岛石板边缘4型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_GRAY_SLAB_EDGE, "灰色安全岛石板边缘");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_SLAB_EDGE_OBLIQUE_1, "黄色斜向安全岛石板边缘1型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_YELLOW_SLAB_EDGE_OBLIQUE_2, "黄色斜向安全岛石板边缘2型");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_GRAY_SLAB, "灰色安全岛石板");
        translationBuilder.add(MunicipalBlocks.SAFETY_ISLAND_GRAY_SLAB_EDGE_OBLIQUE, "灰色斜向安全岛石板边缘");

// 道路栏杆类
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_IRON, "铁质道路栏杆");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_IRON_ENDING_1, "铁质道路栏杆端头1型");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_IRON_ENDING_2, "铁质道路栏杆端头2型");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_IRON_POLE, "铁质道路栏杆立柱");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_IRON_OBLIQUE, "斜向铁质道路栏杆");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_GREEN, "绿色道路栏杆");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_GREEN_ENDING_1, "绿色道路栏杆端头1型");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_GREEN_ENDING_2, "绿色道路栏杆端头2型");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_GREEN_POLE, "绿色道路栏杆立柱");
        translationBuilder.add(MunicipalBlocks.ROAD_RAILINGS_GREEN_OBLIQUE, "斜向绿色道路栏杆");

        translationBuilder.add(MunicipalBlocks.WARNING_NETWORK,"警示网");
        translationBuilder.add(MunicipalBlocks.WARNING_NETWORK_POLE,"警示网立柱");

// 道路封闭护栏类
        translationBuilder.add(MunicipalBlocks.ROAD_CLOSED_BARRICADE_GUARDRAIL_1, "道路封闭护栏1型");
        translationBuilder.add(MunicipalBlocks.ROAD_CLOSED_BARRICADE_GUARDRAIL_2, "道路封闭护栏2型");

// 道路杆件类
        translationBuilder.add(MunicipalBlocks.ROAD_POLE_FOUNDATIONS, "道路杆件基础");
        translationBuilder.add(MunicipalBlocks.ROAD_POLE_LONGITUDINAL, "纵向道路杆件");
        translationBuilder.add(MunicipalBlocks.ROAD_POLE_HORIZONTAL, "横向道路杆件");
        translationBuilder.add(MunicipalBlocks.ROAD_POLE_TSHAPE, "T型道路杆件");
        translationBuilder.add(MunicipalBlocks.ROAD_LIGHT, "道路照明灯");
        translationBuilder.add("block.yunbeiuc.road_light.tooltip","手持魔杖右键点击以切换灯光状态");

// 道路及标线类
        translationBuilder.add(RoadBlocks.ROAD_BLOCK, "道路块");
        translationBuilder.add(RoadBlocks.ROAD_FULL_OF_WHITE,"全白道路");
        translationBuilder.add(RoadBlocks.ROAD_FULL_OF_YELLOW,"全黄道路");
        translationBuilder.add(RoadBlocks.ROAD_WHITE_YELLOW,"白黄道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_LINE, "白色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_DOUBLE_LINE, "白色双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_THICK_LINE, "白色粗标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_LINE, "黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_DOUBLE_LINE, "黄色双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_THICK_LINE, "黄色粗标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_YELLOW_DOUBLE_LINE, "白黄双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_HALF_DOUBLE_LINE, "白色半双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_HALF_DOUBLE_LINE, "黄色半双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_OFFSET_LINE, "白色偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_OFFSET_LINE, "黄色偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_RIGHTANGLE_LINE, "白色直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_RIGHTANGLE_LINE, "黄色直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_YELLOW_RIGHTANGLE_LINE, "白黄直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_NORMAL_RIGHTANGLE_LINE, "白色粗+普通直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_YELLOW_RIGHTANGLE_LINE, "白色粗+黄色直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_YELLOWDOUBLE_RIGHTANGLE_LINE, "白色粗+黄色双实直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_YELLOWDOUBLE_RIGHTANGLE_LINE, "白色+黄色双实直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_BEVEL_LINE, "白色斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_BEVEL_DOUBLE_LINE, "白色斜角双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_BEVEL_THICK_LINE, "白色粗斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_OFFSET_OUT_BEVEL_RIGHTANGLE_LINE, "白色外偏移斜角直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_OFFSET_IN_BEVEL_RIGHTANGLE_LINE, "白色内偏移斜角直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_BEVEL_LINE, "黄色斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_BEVEL_DOUBLE_LINE, "黄色斜角双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_BEVEL_THICK_LINE, "黄色粗斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_OFFSET_OUT_BEVEL_RIGHTANGLE_LINE, "黄色外偏移斜角直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_OFFSET_IN_BEVEL_RIGHTANGLE_LINE, "黄色内偏移斜角直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_RIGHTANGLE_LINE_OFFSET_OUT, "白色直角外偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_RIGHTANGLE_LINE_OFFSET_IN, "白色直角内偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_OFFSET_OUT_RIGHTANGLE_LINE, "白色外偏移直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_OFFSET_IN_RIGHTANGLE_LINE, "白色内偏移直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_RIGHTANGLE_LINE_OFFSET_OUT, "黄色直角外偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_RIGHTANGLE_LINE_OFFSET_IN, "黄色直角内偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_OFFSET_OUT_RIGHTANGLE_LINE, "黄色外偏移直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_OFFSET_IN_RIGHTANGLE_LINE, "黄色内偏移直角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_LINE, "白色T型标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_TSHAPE_LINE, "黄色T型标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_DOUBLE_LINE, "白色T型双实线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_THICK_LINE, "白色粗T型标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_DOUBLE_TSHAPE_LINE, "白色双实T型标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_THICK_TSHAPE_LINE, "白色粗实T型标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_YELLOW_LINE, "白色T型+黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_TSHAPE_WHITE_LINE, "黄色T型+白色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_YELLOWDOUBLE_LINE, "白色T型+黄色双实标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_THICK_TSHAPE_YELLOW_LINE, "白色粗T型+黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_TSHAPE_YELLOWDOUBLE_LINE, "白色粗T型+黄色双实标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_OFFSET_LINE, "白色T型偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_TSHAPE_OFFSET_LINE, "黄色T型偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITEDOUBLE_TSHAPE_OFFSET_LINE, "白色双实T型偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_TSHAPE_OFFSET_LINE, "白色粗T型偏移标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_TSHAPE_OFFSET_YELLOW_LINE, "白色粗T型偏移+黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_TSHAPE_OFFSET_WHITE_LINE, "黄色T型偏移+白色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_TSHAPE_OFFSET_YELLOW_LINE, "白色T型偏移+黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_BEVEL_DB_LINE, "白色斜角双实标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_BEVEL_DB_LINE, "黄色斜角双实标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITENORMAL_AND_BEVEL_DB_LINE, "白色普通+斜角双实标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOWNORMAL_AND_BEVEL_DB_LINE, "黄色普通+斜角双实标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITENORMAL_BEVEL_LINE, "白色普通+斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOWNORMAL_BEVEL_LINE, "黄色普通+斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITENORMAL_BEVEL_YELLOW_LINE, "白色普通+斜角+黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOWNORMAL_BEVEL_WHITE_LINE, "黄色普通+斜角+白色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_BEVEL_LINE, "白色粗+斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOWTHICK_BEVEL_LINE, "黄色粗+斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITETHICK_BEVEL_YELLOW_LINE, "白色粗+斜角+黄色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOWTHICK_BEVEL_WHITE_LINE, "黄色粗+斜角+白色标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_CROSS_LINE, "白色十字标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_CROSS_LINE, "黄色十字标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_LEFT_DIAMOND_SHAPE_LINE, "白色左菱形道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_RIGHT_DIAMOND_SHAPE_LINE, "白色右菱形道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_DOUBLE_DIAMOND_SHAPE_LINE, "白色双菱形道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_LEFT_DIAMOND_SHAPE_LINE, "黄色左菱形道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_DOUBLE_DIAMOND_SHAPE_LINE, "黄色右菱形道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_YELLOW_RIGHT_DIAMOND_SHAPE_LINE, "黄色双菱形道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_THREE_SQUARE_LINE, "白色收费广场减速1道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_SIX_SQUARE_LINE, "白色收费广场减速2道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_WHITE_NINE_SQUARE_LINE, "白色收费广场减速3道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_AUTO_BEVEL_LINE, "自动斜角标线道路");
        translationBuilder.add(RoadBlocks.ROAD_WITH_AUTO_RIGHTANGLE_LINE, "自动直角标线道路");

        translationBuilder.add(RoadBlocks.STRAIGHT_GROUND_MARK, "直行标记");
        translationBuilder.add(RoadBlocks.STRAIGHT_LEFT_TURN_GROUND_MARK, "直行左转标记");
        translationBuilder.add(RoadBlocks.LEFT_TURN_GROUND_MARK, "左转标记");
        translationBuilder.add(RoadBlocks.STRAIGHT_RIGHT_TURN_GROUND_MARK, "直行右转标记");
        translationBuilder.add(RoadBlocks.RIGHT_TURN_GROUND_MARK, "右转标记");
        translationBuilder.add(RoadBlocks.STRAIGHT_LEFT_RIGHT_TURN_GROUND_MARK, "直行左右转标记");
        translationBuilder.add(RoadBlocks.LEFT_TURN_AROUND_SINGLE_GROUND_MARK, "前方掉头标记");
        translationBuilder.add(RoadBlocks.STRAIGHT_LEFT_TURN_AROUND_GROUND_MARK, "前方可直行掉头标记");
        translationBuilder.add(RoadBlocks.LEFT_TURN_AROUND_GROUND_MARK, "前方可左转掉头标记");
        translationBuilder.add(RoadBlocks.LEFT_RIGHT_TURN_GROUND_MARK, "左右转标记");
        translationBuilder.add(RoadBlocks.LEFT_TURN_MERGE_GROUND_MARK, "左合流标记");
        translationBuilder.add(RoadBlocks.RIGHT_TURN_MERGE_GROUND_MARK, "右合流标记");
        translationBuilder.add(RoadBlocks.SLOWDOWN_ANNOUNCEMENT_GROUND_MARK, "人行横道预告标记");
        translationBuilder.add(RoadBlocks.DISTANCE_CONFIRMATION_GROUND_MARK, "折线车距确认标记");
        translationBuilder.add(RoadBlocks.TAXI_1_GROUND_MARK, "“出”标记");
        translationBuilder.add(RoadBlocks.TAXI_2_GROUND_MARK, "“租”标记");
        translationBuilder.add(RoadBlocks.VEHICLE_GROUND_MARK, "“车”标记");
        translationBuilder.add(RoadBlocks.DISABLED_PEOPLE_GROUND_MARK, "残疾人专用标记");
        translationBuilder.add(RoadBlocks.NON_MOTOR_VEHICLES_GROUND_MARK, "非机动车标记");
        translationBuilder.add(RoadBlocks.BUS_1_GROUND_MARK, "“公”标记");
        translationBuilder.add(RoadBlocks.BUS_2_GROUND_MARK, "“交”标记");
        translationBuilder.add(RoadBlocks.SCHOOL_BUS_1_GROUND_MARK, "“校”标记");
        translationBuilder.add(RoadBlocks.LARGE_SPEED_BUMP_GROUND_MARK, "大型减速丘标记");
        translationBuilder.add(RoadBlocks.SMALL_SPEED_BUMP_GROUND_MARK, "小型减速丘标记");
        translationBuilder.add(RoadBlocks.WHITE_040_GROUND_MARK, "最低限速40km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_050_GROUND_MARK, "最低限速50km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_060_GROUND_MARK, "最低限速60km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_070_GROUND_MARK, "最低限速70km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_080_GROUND_MARK, "最低限速80km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_090_GROUND_MARK, "最低限速90km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_100_GROUND_MARK, "最低限速100km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_110_GROUND_MARK, "最低限速110km/h标记");
        translationBuilder.add(RoadBlocks.WHITE_120_GROUND_MARK, "最低限速120km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_040_GROUND_MARK, "最高限速40km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_050_GROUND_MARK, "最高限速50km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_060_GROUND_MARK, "最高限速60km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_070_GROUND_MARK, "最高限速70km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_080_GROUND_MARK, "最高限速80km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_090_GROUND_MARK, "最高限速90km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_100_GROUND_MARK, "最高限速100km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_110_GROUND_MARK, "最高限速110km/h标记");
        translationBuilder.add(RoadBlocks.YELLOW_120_GROUND_MARK, "最高限速120km/h标记");
        translationBuilder.add(RoadBlocks.ELECTRIC_VEHICLE_GROUND_MARK, "电动自行车标记");
        translationBuilder.add(RoadBlocks.PEDESTRIAN_GROUND_MARK, "行人标记");
        translationBuilder.add(RoadBlocks.STOP_AND_YIELD_GROUND_MARK, "停车让行标记");
        translationBuilder.add(RoadBlocks.HOV_1_GROUND_MARK, "“多”标记");
        translationBuilder.add(RoadBlocks.HOV_2_GROUND_MARK, "“乘”标记");
        translationBuilder.add(RoadBlocks.HOV_3_GROUND_MARK, "“客”标记");
        translationBuilder.add(RoadBlocks.HOV_4_GROUND_MARK, "“3+”标记");
        translationBuilder.add(RoadBlocks.HOV_5_GROUND_MARK, "“5+”标记");
        translationBuilder.add(RoadBlocks.MANHOLE_COVER, "井盖");

// 道路杆件附属类
        translationBuilder.add(MunicipalBlocks.ROAD_POLE_TEXT_DISPLAY, "道路杆件文字显示屏");
        translationBuilder.add(MunicipalBlocks.ROAD_POLE_FLAG, "道路杆件旗帜");
        translationBuilder.add("text.yunbeiuc.flag_selection.title", "旗帜选择");
        translationBuilder.add("text.yunbeiuc.flag_selection.current_selection", "当前选择：%s");
        translationBuilder.add("text.yunbeiuc.flag_selection.preview_panel", "旗帜预览");
        translationBuilder.add("text.yunbeiuc.flag_selection.save_button", "保存");
        translationBuilder.add("text.yunbeiuc.flag_selection.load_failed", "加载失败");

        translationBuilder.add(SignBlocks.SIGN_STOP, "停车让行标志");
        translationBuilder.add(SignBlocks.SIGN_YIELD, "减速让行标志");
        translationBuilder.add(SignBlocks.SIGN_YIELD_TO_ONCOMING_TRAFFIC, "会车让行标志");
        translationBuilder.add(SignBlocks.SIGN_NO_ALL, "禁止通行标志");
        translationBuilder.add(SignBlocks.SIGN_NO_ENTRY, "禁止驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_MOTOR_VEHICLES, "禁止机动车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_LARGE_BUS, "禁止大型载客汽车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_SMALL_PASSENGER_CAR, "禁止小型载客汽车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_TRUCK, "禁止载货汽车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_TRAILER, "禁止挂车、半挂车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_TRACTOR, "禁止拖拉机驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_THREE_WHEELED_VEHICLE, "禁止三轮汽车、低速货车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_MOTORCYCLE, "禁止摩托车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_NON_MOTOR_VEHICLES, "禁止非机动车进入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_ELECTRIC_VEHICLE, "禁止电动自行车进入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_ANIMAL_DRAWN_CART, "禁止畜力车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_TRICYCLE, "禁止三轮车驶入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_HUMAN_POWERED_PASSENGER_TRICYCLE, "禁止人力客运三轮车进入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_HUMAN_POWERED_CARGO_TRICYCLE, "禁止人力货运三轮车标志");
        translationBuilder.add(SignBlocks.SIGN_NO_RICKSHAW, "禁止人力车进入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_PEDESTRIAN, "禁止行人进入标志");
        translationBuilder.add(SignBlocks.SIGN_NO_LEFT_TURN, "禁止向左转弯标志");
        translationBuilder.add(SignBlocks.SIGN_NO_STRAIGHT, "禁止直行标志");
        translationBuilder.add(SignBlocks.SIGN_NO_RIGHT_TURN, "禁止向右转弯标志");
        translationBuilder.add(SignBlocks.SIGN_NO_LEFT_RIGHT_TURN, "禁止向左和向右转弯");
        translationBuilder.add(SignBlocks.SIGN_NO_STRAIGHT_LEFT_TURN, "禁止直行和向左转弯标志");
        translationBuilder.add(SignBlocks.SIGN_NO_STRAIGHT_RIGHT_TURN, "禁止直行和向右转弯标志");
        translationBuilder.add(SignBlocks.SIGN_NO_SINGLE_LEFT_TURN_AROUND, "禁止掉头标志");
        translationBuilder.add(SignBlocks.SIGN_NO_OVERTAKE, "禁止超车标志");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_OVERTAKE, "解除禁止超车标志");
        translationBuilder.add(SignBlocks.SIGN_NO_PARKING, "禁止车辆停放标志");
        translationBuilder.add(SignBlocks.SIGN_NO_PARKING_LONG_TIME, "禁止车辆长时停放标志");
        translationBuilder.add(SignBlocks.SIGN_NO_HONK_HORN, "禁止鸣喇叭标志");
        translationBuilder.add(SignBlocks.SIGN_WIDTH_LIMIT_20, "限制宽度标志：2.0米");
        translationBuilder.add(SignBlocks.SIGN_WIDTH_LIMIT_25, "限制宽度标志：2.5米");
        translationBuilder.add(SignBlocks.SIGN_WIDTH_LIMIT_30, "限制宽度标志：3.0米");
        translationBuilder.add(SignBlocks.SIGN_WIDTH_LIMIT_35, "限制宽度标志：3.5米");
        translationBuilder.add(SignBlocks.SIGN_WIDTH_LIMIT_40, "限制宽度标志：4.0米");
        translationBuilder.add(SignBlocks.SIGN_WIDTH_LIMIT_45, "限制宽度标志：4.5米");
        translationBuilder.add(SignBlocks.SIGN_HEIGHT_LIMIT_20, "限制高度标志：2.0米");
        translationBuilder.add(SignBlocks.SIGN_HEIGHT_LIMIT_25, "限制高度标志：2.5米");
        translationBuilder.add(SignBlocks.SIGN_HEIGHT_LIMIT_30, "限制高度标志：3.0米");
        translationBuilder.add(SignBlocks.SIGN_HEIGHT_LIMIT_35, "限制高度标志：3.5米");
        translationBuilder.add(SignBlocks.SIGN_HEIGHT_LIMIT_40, "限制高度标志：4.0米");
        translationBuilder.add(SignBlocks.SIGN_HEIGHT_LIMIT_45, "限制高度标志：4.5米");
        translationBuilder.add(SignBlocks.SIGN_WEIGHT_LIMIT_10, "限制质量标志：10吨");
        translationBuilder.add(SignBlocks.SIGN_WEIGHT_LIMIT_20, "限制质量标志：20吨");
        translationBuilder.add(SignBlocks.SIGN_WEIGHT_LIMIT_30, "限制质量标志：30吨");
        translationBuilder.add(SignBlocks.SIGN_WEIGHT_LIMIT_40, "限制质量标志：40吨");
        translationBuilder.add(SignBlocks.SIGN_ALEX_WEIGHT_LIMIT_10, "限制轴重标志：10吨");
        translationBuilder.add(SignBlocks.SIGN_ALEX_WEIGHT_LIMIT_20, "限制轴重标志：20吨");
        translationBuilder.add(SignBlocks.SIGN_ALEX_WEIGHT_LIMIT_30, "限制轴重标志：30吨");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_005, "限制速度标志：5公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_010, "限制速度标志：10公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_020, "限制速度标志：20公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_030, "限制速度标志：30公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_040, "限制速度标志：40公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_050, "限制速度标志：50公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_060, "限制速度标志：60公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_070, "限制速度标志：70公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_080, "限制速度标志：80公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_090, "限制速度标志：90公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_100, "限制速度标志：100公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_110, "限制速度标志：110公里/小时");
        translationBuilder.add(SignBlocks.SIGN_SPEED_LIMIT_120, "限制速度标志：120公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_005, "解除限制速度标志：5公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_010, "解除限制速度标志：10公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_020, "解除限制速度标志：20公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_030, "解除限制速度标志：30公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_040, "解除限制速度标志：40公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_050, "解除限制速度标志：50公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_060, "解除限制速度标志：60公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_070, "解除限制速度标志：70公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_080, "解除限制速度标志：80公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_090, "解除限制速度标志：90公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_100, "解除限制速度标志：100公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_110, "解除限制速度标志：110公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_120, "解除限制速度标志：120公里/小时");
        translationBuilder.add(SignBlocks.SIGN_CHECK, "停车检查标志");
        translationBuilder.add(SignBlocks.SIGN_PORT_CHECK, "口岸停车检查标志");
        translationBuilder.add(SignBlocks.SIGN_NO_HAZARDOUS_MATERIALS_TRANSPORT_VEHICLE, "禁止危险物品运输车辆驶入标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_STRAIGHT, "直行标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LEFT_TURN, "向左转弯标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_RIGHT_TURN, "向右转弯标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_STRAIGHT_LEFT_TURN, "直行和向左转弯标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_STRAIGHT_RIGHT_TURN, "直行和向右转弯标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LEFT_RIGHT_TURN, "向左和向右转弯标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_RIGHT_SIDE_MEDIAN_STRIP, "分隔带右侧行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LEFT_SIDE_MEDIAN_STRIP, "分隔带左侧行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_ROUNDABOUT, "环岛行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_ONE_WAY_STREET_LEFT_RIGHT, "单行路（向左或向右）标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_ONE_WAY_STREET_STRAIGHT, "单行路（直行）标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_HONK_HORN, "鸣喇叭标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_HEADLIGHTS, "开车灯标志");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_005, "最低限速标志：5公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_010, "最低限速标志：10公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_020, "最低限速标志：20公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_030, "最低限速标志：30公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_040, "最低限速标志：40公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_050, "最低限速标志：50公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_060, "最低限速标志：60公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_070, "最低限速标志：70公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_080, "最低限速标志：80公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_090, "最低限速标志：90公里/小时");
        translationBuilder.add(SignBlocks.SIGN_MIN_SPEED_LIMIT_100, "最低限速标志：100公里/小时");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_YIELD_TO_ONCOMING_TRAFFIC, "会车先行标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_ZEBRA_CROSSING, "人行横道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_ZEBRA_CROSSING_FLUORESCENCE, "荧光人行横道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_RIGHT_TURN, "右转车道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LEFT_TURN, "左转车道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_STRAIGHT, "直行车道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_STRAIGHT_RIGHT_TURN, "直行和右转合用车道");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_STRAIGHT_LEFT_TURN, "直行和左转合用车道");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SINGLE_LEFT_TURN_AROUND, "掉头车道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LEFT_TURN_AROUND, "掉头和左转合用车道");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_MOTOR_VEHICLES, "机动车行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES, "机动车车道标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_STRAIGHT, "机动车车道标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_LEFT_SIDE_MEDIAN_STRIP, "机动车车道标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_RIGHT_SIDE_MEDIAN_STRIP, "机动车车道标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR, "小型客车车道标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_STRAIGHT, "小型客车车道标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_LEFT_SIDE_MEDIAN_STRIP, "小型客车车道标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_RIGHT_SIDE_MEDIAN_STRIP, "小型客车车道标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS, "公交专用车道标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_STRAIGHT, "公交专用车道标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_LEFT_SIDE_MEDIAN_STRIP, "公交专用车道标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_RIGHT_SIDE_MEDIAN_STRIP, "公交专用车道标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT, "公交专用车道（文字）标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_STRAIGHT, "公交专用车道（文字）标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_LEFT_SIDE_MEDIAN_STRIP, "公交专用车道（文字）标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_RIGHT_SIDE_MEDIAN_STRIP, "公交专用车道（文字）标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT, "快速公交系统(BRT)专用车道标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_STRAIGHT, "快速公交系统(BRT)专用车道标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_LEFT_SIDE_MEDIAN_STRIP, "快速公交系统(BRT)专用车道标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_RIGHT_SIDE_MEDIAN_STRIP, "快速公交系统(BRT)专用车道标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_TRAM_STRAIGHT, "有轨电车专用车道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_HOV, "多乘员车辆(HOV)专用车道标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_NON_MOTOR_VEHICLES, "非机动车行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES, "非机动车车道标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_STRAIGHT, "非机动车车道标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_LEFT_SIDE_MEDIAN_STRIP, "非机动车车道标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_RIGHT_SIDE_MEDIAN_STRIP, "非机动车车道标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_ELECTRIC_VEHICLE, "电动自行车行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE, "电动自行车车道标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_STRAIGHT, "电动自行车车道标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_LEFT_SIDE_MEDIAN_STRIP, "电动自行车车道标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_RIGHT_SIDE_MEDIAN_STRIP, "电动自行车车道标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PEDESTRIAN, "行人标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_1, "非机动车与行人通行标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_2, "非机动车与行人通行标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_3, "非机动车与行人通行标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PROMOTION_NON_MOTOR_VEHICLES, "非机动车推行标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PROMOTION_DRIVE_RIGHT, "靠右侧车道行驶标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_1, "停车位标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_2, "停车位标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_3, "停车位标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_4, "停车位标志4");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_DISABLED, "残疾人专用停车位标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_SCHOOL_BUS, "校车专用停车位标志、校车停靠站点标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_SCHOOL_BUS_WUXI, "无锡校园定制公交站点标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_SCHOOL_BUS_FLUORESCENCE, "荧光校车专用停车位标志、荧光校车停靠站点标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_TAXI, "出租车专用停车位标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_NON_MOTOR_VEHICLE, "非机动车专用停车位标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_BUS, "公交车专用停车位标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_CHARGING, "充电停车位标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PARKING_COMPANY, "专属停车位标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_TURN_AROUND, "允许掉头标志");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PAVED_SHOULDER_1, "硬路肩允许行驶标志1");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PAVED_SHOULDER_2, "硬路肩允许行驶标志2");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_PAVED_SHOULDER_3, "硬路肩允许行驶标志3");
        translationBuilder.add(SignBlocks.SIGN_INDICATION_OK_TRUCK, "货车通行标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_1, "交叉路口标志1");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_2, "交叉路口标志2");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_3, "交叉路口标志3");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_4, "交叉路口标志4");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_5, "交叉路口标志5");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_6, "交叉路口标志6");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_7, "交叉路口标志7");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_8, "交叉路口标志8");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_9, "交叉路口标志9");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_10, "交叉路口标志10");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSING_11, "交叉路口标志11");
        translationBuilder.add(SignBlocks.SIGN_WARNING_SHARP_TURN_1, "向左急弯路标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_SHARP_TURN_2, "向右急弯路标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_REVERSE_DETOUR_1, "反向弯路标志1");
        translationBuilder.add(SignBlocks.SIGN_WARNING_REVERSE_DETOUR_2, "反向弯路标志2");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CONTINUOUS_WINDING_ROADS_1, "连续弯路标志1");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CONTINUOU_WINDING_ROADS_2, "连续弯路标志2");
        translationBuilder.add(SignBlocks.SIGN_WARNING_STEEP_SLOPE_UP, "上陡坡标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_STEEP_SLOPE_DOWN, "下陡坡标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CONTINUOUS_DOWNHILL, "连续下坡标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_NARROW_ROAD_DOUBLE, "两侧变窄标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_NARROW_ROAD_LEFT, "左侧变窄标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_NARROW_ROAD_RIGHT, "右侧变窄标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_NARROW_BRIDGE, "窄桥标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_TWO_WAY_TRAFFIC, "双向交通标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ZEBRA_CROSSING, "注意行人标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ZEBRA_CROSSING_FLUORESCENCE, "荧光注注意行人标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CHILDREN, "注意儿童标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CHILDREN_FLUORESCENCE, "荧光注意儿童标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DISABLED, "注意残疾人标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DISABLED_FLUORESCENCE, "荧光注意残疾人标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_NON_MOTOR_VEHICLES, "注意非机动车标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ELECTRIC_VEHICLE, "注意电动自行车标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_LIVESTOCK, "注意牲畜标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_WILDLIFE, "注意野生动物标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_TRAFFIC_LIGHTS, "注意信号灯标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_FALLING_ROCKS_LEFT, "注意左侧落石标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_FALLING_ROCKS_RIGHT, "注意右侧落石标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CROSSWIND, "注意横风标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_SLIPPERY, "易滑标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_PERILOUS_ROAD_ALONG_THE_MOUNTAIN_LEFT, "左侧傍山险路标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_PERILOUS_ROAD_ALONG_THE_MOUNTAIN_RIGHT, "右侧傍山险路标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_EMBANKMENT_ROAD_LEFT, "堤坝路标志1");
        translationBuilder.add(SignBlocks.SIGN_WARNING_EMBANKMENT_ROAD_RIGHT, "堤坝路标志2");
        translationBuilder.add(SignBlocks.SIGN_WARNING_VILLAGE, "村庄标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_TUNNEL, "隧道标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CAMEL_BACK_BRIDGE, "驼峰桥标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ROAD_UNEVEN, "路面不平标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_SPEED_BUMP, "减速丘标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ROAD_WET, "过水路面（或漫水桥）标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_SOMEONE_GUARDING_THE_RAILWAY_CROSSING, "有人看守铁路道口标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_UNMANNED_GUARDING_THE_RAILWAY_CROSSING, "无人看守铁路道口标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ACCIDENT_PRONE_ROAD, "事故易发路段标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DETOUR_DOUBLE, "左右绕行障碍物标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DETOUR_LEFT, "左侧绕行障碍物标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DETOUR_RIGHT, "右侧绕行障碍物标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DANGEROUS, "注意危险标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CONSTRUCTION, "施工标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ACCIDENT, "交通事故管理标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_TIDAL_LANE, "注意潮汐车道标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_DISTANCE_BETWEEN_VEHICLES, "注意保持车距标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CONFLUENCE_LEFT, "注意合流标志1");
        translationBuilder.add(SignBlocks.SIGN_WARNING_CONFLUENCE_RIGHT, "注意合流标志2");
        translationBuilder.add(SignBlocks.SIGN_WARING_LESS_3_TO_2, "注意车道数变少标志（3变2）");
        translationBuilder.add(SignBlocks.SIGN_WARING_LESS_4_TO_3, "注意车道数变少标志（4变3）");
        translationBuilder.add(SignBlocks.SIGN_WARNING_EMERGENCY_LANE_1, "避险车道标志1");
        translationBuilder.add(SignBlocks.SIGN_WARNING_EMERGENCY_LANE_2, "避险车道标志2");
        translationBuilder.add(SignBlocks.SIGN_WARNING_ROAD_ICY, "注意路面结冰标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_WEATHER_RAINY_SNOWY, "注意雨（雪）天标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_WEATHER_FOGGY, "注意雾天标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_WEATHER_THUNDER, "注意不利气象条件标志");
        translationBuilder.add(SignBlocks.SIGN_WARNING_VEHICLES_QUEUED_AHEAD, "注意前方车辆排队标志");
        translationBuilder.add(SignBlocks.ZONES_BOARD_BUS, "公交车专用区域牌");
        translationBuilder.add(SignBlocks.ZONES_BOARD_CHARGING, "充电专用区域牌");
        translationBuilder.add(SignBlocks.ZONES_BOARD_COMPANY, "单位专属区域牌");
        translationBuilder.add(SignBlocks.ZONES_BOARD_DISABLED, "残疾人专用区域牌");
        translationBuilder.add(SignBlocks.ZONES_BOARD_NON_MOTOR_VEHICLES, "非机动车专用区域牌");
        translationBuilder.add(SignBlocks.ZONES_BOARD_SCHOOL, "学校区域牌");
        translationBuilder.add(SignBlocks.ZONES_BOARD_SCHOOL_BUS_1, "校车专用区域牌1");
        translationBuilder.add(SignBlocks.ZONES_BOARD_SCHOOL_BUS_2, "校车专用区域牌2");
        translationBuilder.add(SignBlocks.ZONES_BOARD_TAXI, "出租车专用区域牌");

        translationBuilder.add("itemGroup.yunbeiuc_municipal_group","云北城建 | 市政设施");
        translationBuilder.add("itemGroup.yunbeiuc_rb_group","云北城建 | 道路方块");
        translationBuilder.add("itemGroup.yunbeiuc_sign_group","云北城建 | 道路标识");
        translationBuilder.add("itemGroup.yunbeiuc_wand_group","云北城建 | 魔杖工具");
    }
}
